name: Artifact Lesson

on:
  workflow_dispatch:

jobs:  
  create_artifact:
    name: Create Artifact
    runs-on: ubuntu-latest
    steps:
      - name: step 1 create artifacts
        run: echo "This is a text in a new artifact" > artifact.txt
      - name: Upload artifact step 2
        uses: actions/upload-artifact@v4
        with:
          name: Artifact-demo
          path: artifact.txt

  dowload_artifact:
    name: Download Artifact
    needs: create_artifact
    runs-on: ubuntu-latest
    steps:
      - name: step 1 download artifact
        uses: actions/download-artifact@v5
        with:
          name: Artifact-demo
          path: .
      - name: Print artifact step 2
        run: cat artifact.txt

    

    
